# Wordle Solver

In [1]:
from wordle import ScoreBoard, Solver

%load_ext autoreload
%autoreload 2

### Play Wordle

In [2]:
# initialize the solver
solver = Solver()

# feedback from the guesses played so far (positions are 1-indexed)
green_letters = "lien"
green_positions = [1, 2, 4, 5]
yellow_letters = "en"
yellow_positions = [5, 3]
gray_letters = "tarykm"

# find words consistent with the feedback
words = solver.find_words(
    green_letters,
    green_positions,
    yellow_letters,
    yellow_positions,
    gray_letters,
    answer_word_list=False,
)
print(f"Number of possible words: {len(words)}")

# rank the next word to play
solver.choose_word_to_play(word_threshold=2)

Number of possible words: 1

    Word  Entropy  Score
0  LIVEN      0.0    0.0

In [3]:
# # reset score
# board.reset()

In [4]:
# repetitive letters
letters_df = solver.repetitive_letters()
print(letters_df.to_string(index=False))

Letters  Count
      L      1
      I      1
      V      1
      E      1
      N      1

In [5]:
board = ScoreBoard()
df = board.load()
df

     Names  Games_Won
0   Murilo        543
1  Barbara        250
2     Draw        541

In [6]:
# update score
score_df = board.update()
score_df

'' is not one of M/B/D; scores unchanged.

     Names  Games_Won
0   Murilo        543
1  Barbara        250
2     Draw        541

In [7]:
# print results
print(score_df.to_string(index=False))

  Names  Games_Won
 Murilo        543
Barbara        250
   Draw        541

In [8]:
# git commit message
commit_message = board.commit_message(word=solver.answer)
print(commit_message)

git commit -m "updated wordle 543-250-541, word=LIVEN"

#### Set custom score

In [9]:
# help(board.set_scores)

In [10]:
# set custom score
# df = board.set_scores(Murilo=477, Barbara=215, Draw=473)
# df

#### Reset score

In [11]:
# # reset score
# board.reset()